# Use the official Golang image
FROM golang:1.25-alpine AS development

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum to download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Install air for live-reloading
# The -b flag installs air in $GOPATH/bin, which is in the PATH
RUN go install github.com/air-verse/air@latest

# Copy the rest of the source code
COPY . .

# Expose the port the app runs on
EXPOSE 8080
